#!/bin/bash

docker rmi -f sprintngnx
docker stop sprintngnx
docker rm sprintngnx
echo "docker build -t sprintngnx ."
docker build -t sprintngnx .

echo "docker run --name sprintngnx --rm -p 80:80 -ti sprintngnx"
echo "docker run --name sprintngnx --rm -p 80:80 -d sprintngnx"
#docker run --name sprintngnx --rm -p 80:80 -ti sprintngnx
#docker run --name sprintngnx --rm -p 80:80 -ti sprintngnx

